language: bash
services: docker

install:
  - git clone https://github.com/gilir/rpi-ghost ~/rpi-images

before_script:
  - env | sort
  - image='rpi/gilir-ghost'

script:
  - docker build -t "$image" .
  - ~/rpi-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
