version: '2'

services:
  ghost:
    image: gilir/rpi-ghost
    container_name: ghost
    ports:
      - "2368:2368"
    labels:
      - "traefik.frontend.rule=Host:lavergne.online,blog.lavergne.online,ghost.lavergne.online"
    volumes:
      # Blog data, host on ghost_data volume
      - ghost_data:/var/lib/ghost
    restart: always
    networks:
      - proxy-network

# Support for reverse proxy - Common network interface for all containers
networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  ghost_data:
    external: true
