version: '2'

services:
  ghost:
    image: gilir/arm64-ghost
    container_name: ghost
    ports:
      - 12368:2368
    labels:
      - traefik.frontend.rule=Host:blog.lavergne.online,ghost.lavergne.online
      - traefik.docker.network=proxy-network
      - traefik.port=2368
      - traefik.backend=ghost
      - traefik.frontend.entryPoints=https,http
    volumes:
      # Blog data, host on ghost_data volume
      - ghost_data:/ghost/content/
    restart: always
    networks:
      - proxy-network

# Support for reverse proxy - Common network interface for all containers
networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  ghost_data:
    external: true
